# Grantmaker settings
foundation_name: The Monica Chibuogu Nneji Foundation
foundation_tagline: We are on a mission to invest in the health, education, and mobility of communities in need.
grant_application_login: https://paypal.me/Nneji

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
profile_twitter: https://paypal.me/Nneji
profile_facebook: 
profile_instagram: 
profile_github: 

# Site settings
title: # Defaults to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  The Monica Chibuogu Nneji Foundation is a 501(c)(3) nonprofit public charity on a mission to invest in the health, education, and mobility of communities in need.

# Google settings
live: false # enter 'true' when you're ready for the site to be indexed by Google and other web crawlers

# Jekyll settings
baseurl: # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://smartergiving.org # Typically http://www.yourdomain.org
collections:
  featured-cards:
    output: false
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
  - /images/photoshop-helpers
