# Grantmaker settings
foundation_name: The Monica Chibuogu Nneji Foundation, Inc.
foundation_tagline: 
paypal_donation: https://paypal.me/Nneji

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
profile_paypal: https://paypal.me/Nneji
profile_amazon: https://smile.amazon.com/ch/85-1546329
profile_instagram: 
profile_github: 

# Site settings
title: The Monica Chibuogu Nneji Foundation, Inc. # Defaults to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  The Monica Chibuogu Nneji Foundation, Inc. is a 501(c)(3) nonprofit public charity on a mission to invest in the health, education, and upward mobility of communities in need.

# Google settings
live: true # enter 'true' when you're ready for the site to be indexed by Google and other web crawlers

# Jekyll settings
baseurl: # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://nnejifoundation.github.io # Typically http://www.yourdomain.org, change to nnejifoundation.org when ready
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
  - /images/photoshop-helpers
